apiVersion: v1
kind: ConfigMap
metadata:
  name: converter-configmap
data:
  MP3_QUEUE: "mp3"
  VIDEO_QUEUE: "video"
  MONGODB_URI: "mongodb://jaro:jaro1234@18.205.117.117:30005/mp3s?authSource=admin" #nodeip:nodeport
