apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
data:
  AUTH_SVC_ADDRESS: "auth:5000"
  MONGODB_VIDEOS_URI: "mongodb://jaro:jaro1234@18.205.117.117:30005/videos?authSource=admin"
  MONGODB_MP3S_URI: "mongodb://jaro:jaro1234@18.205.117.117:30005/mp3s?authSource=admin"
